server:
    port: 8080

spring:
    data:
        mongodb:
            host: ${mongo.host}
            port: 27017
            database: TatilKiralamaDB2
            username: bilgeUser #java13mongodbusername ismiyle ortam degiskeni olarak eklenecek
            password: bilgeUser* #java13mongodbpassword ismiyle ortam degiskeni olarak eklenecek
    mail:
        username: ${java13mailusername} #java13mailusername ismiyle ortam degiskeni olarak eklenecek
        password: ${java13mailpassword} #java13mailpassword ismiyle ortam degiskeni olarak eklenecek.
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
springApp:
    redis:
        host: ${redis.host}


